### ISSUE TITLE
OmniRig has several Rig types for the same transceiver model

### ISSUE THREAD

**Issue by zstadler** [cniesen/IcomClockOmniRig#10]
Some Transceiver models have multiple OmniRig types. For example, the distributed [INI files for OmniRig](http://www.dxatlas.com/OmniRig/Files/RigIni.zip) has the following:

* IC-7100
  * IC-7100-DATA-FIL1
  * IC-7100
  * IC-7100e4-DATA
  * IC-7100e4
* IC-7300
  * IC-7300-DATA
  * IC-7300
* IC-7600
  * IC-7600
  * IC-7600v2-DATA
  * IC-7600v2
* IC-7610
  * IC-7610-DATA-FIL1
  * IC-7610-DATA
  * IC-7610
* IC-7700
  * IC-7700
  * IC-7700v2-DATA
  * IC-7700v2
* IC-7850
  * IC-7850-DATA-FIL1
  * IC-7850-DATA
  * IC-7850
* IC-7851
  * IC-7851-DATA-FIL1
  * IC-7851-DATA
  * IC-7851
* IC-9700
  * IC-9700-DATA
  * IC-9700-SAT
  * IC-9700

Using any of the OmniRig variants requires the use of the program's discouraged `-f` flag.

It would be safer if the check for the transceiver model would accept them by allowing the transceiver model name to be a prefix of the OmniRig name.

**Comment by cniesen** [comment]
That idea works for the currently supported transceivers by IcomClockOmniRig but might cause issue in the future.

Example:
IC-77 vs IC-775
IC-761 vs IC-7610
FT-100 vs FT-1000

Adding this functionality now and removing it later would cause backwards compatibility (i.e. people's configuration would all the sudden not work anymore).

If the usage of the -f flag is a concern then keeping a mapping table as you listed above would be better.  It doesn't introduce issues with other model numbers and is a little safer than your original suggestion.  The -f flag would still be kept just in case.

**Comment by zstadler** [comment]
Thanks for your comment! Let me suggest slightly different approach.

When IcomClockOmniRig is used, we can probably assume that OmniRig is working well with the user's other programs.

A such, IcomClockOmniRig can use the OmniRig profile name as the default model name. This would replace the hard-coded IC-7300 default model. As a result, some people who use IcomClockOmniRig with rig other than IC-7300 will be able to use it out-of-the-box. Clearly, there should be an error if there is no IcomClockOmniRig model with the OmniRig profile name.

Taking another step forward in this direction, IcomClockOmniRig can select as its default model, the one that has the longest-matching prefix with the OmniRig profile name.

**Comment by cniesen** [comment]
Here's my draft implementation of your idea to default the transceiver model to whatever is set in OmniRig.
https://github.com/cniesen/IcomClockOmniRig/pull/12

I still don't like the idea of substring matching.  Since rig ini files aren't created by mass, rarely there is an update, I went with a lookup table.  That way the auto matching should be solid.

With that the `-f` flag is obsolete since nobody normally needs to specify the rig type manually via the `-m` flag.  I'll probably remove the `-f` flag and the `CheckTransceiverModel` check.

**Comment by zstadler** [comment]
Thanks @cniesen for considering my proposal.

> I still don't like the idea of substring matching. Since rig ini files aren't created by mass, rarely there is an update, I went with a lookup table. That way the auto matching should be solid.

It is this rare update of the OmniRig ini file that concerns me. 

For example, the DATA variants if the FT-7300 are aimed mostly for RTTY and lacked important settings for FT8. I've created a new profile and sent it to the OmniRig author, but got no response.

Clearly, the lookup table is much more robust that prefix matching. However, for assisting me and other people how need their own version of the ini files, I'd suggest that a `<TransceiverModel>-` prefix, with a separation dash,  will be also be used when the lookup fails. I hope this addresses your valid concern about forward compatibility.

**Comment by cniesen** [comment]
@zstadler Thanks for working with me on this.  I updated the program which should do what you're hoping for.  A new release is out.

**Comment by zstadler** [comment]
Thank you @cniesen for implementing this enhancement. It works like charm! 

Using the new version out-of-the-box with "'IC-7300-FT8" rig type:

```
 ::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::
 ::                                                                          ::
 ::   IcomClockOmniRig 2.1  -  https://github.com/cniesen/IcomClockOmniRig   ::
 ::                                                                          ::
 ::    A program to set the Icom tranceiver clock to your computer's time    ::
 ::                                                                          ::
 ::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::

Program Options:
    Using OmniRig version: 1 (by VE3NEA)
    Using OmniRig rig: 1
    Using transceiver model: IC-7300
    Using transceiver address: 94
    Reverse clock and UTC time: no

OmniRig Software Version: 1.20
OmniRig Interface Version: 1.1
Rig 1
    Rig Type: IC-7300-FT8
    Status:   ST_ONLINE
Rig 2
    Rig Type: NONE
    Status:   ST_NOTCONFIGURED

Waiting for the full minute to set time
Sending command: FEFE94E01A0500951644FD - Rig response: OK
Sending command: FEFE94E01A05009420211109FD - Rig response: OK
Sending command: FEFE94E01A050096020000FD - Rig response: OK
```
